"""initial migration

Revision ID: 6782f06ecca1
Revises: 343bb188ff78
Create Date: 2024-06-29 10:09:46.242408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6782f06ecca1'
down_revision: Union[str, None] = '343bb188ff78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('topic_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('topic_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('topic_id'),
    sa.UniqueConstraint('topic_name')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.BIGINT(), nullable=False),
    sa.Column('with_pictures', sa.Boolean(), nullable=False),
    sa.Column('question_type', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('option_a', sa.String(), nullable=False),
    sa.Column('option_b', sa.String(), nullable=False),
    sa.Column('option_c', sa.String(), nullable=False),
    sa.Column('option_d', sa.String(), nullable=False),
    sa.Column('option_e', sa.String(), nullable=True),
    sa.Column('option_f', sa.String(), nullable=True),
    sa.Column('option_g', sa.String(), nullable=True),
    sa.Column('option_h', sa.String(), nullable=True),
    sa.Column('correct_option', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('skippedquestions',
    sa.Column('skipped_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('question_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('skipped_id')
    )
    op.create_table('useranswers',
    sa.Column('answer_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('question_id', sa.BIGINT(), nullable=False),
    sa.Column('selected_option', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.add_column('users', sa.Column('current_topic', sa.BIGINT(), nullable=True))
    op.add_column('users', sa.Column('current_question_index', sa.BIGINT(), nullable=False))
    op.add_column('users', sa.Column('progress_reset', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'users', 'topics', ['current_topic'], ['topic_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'progress_reset')
    op.drop_column('users', 'current_question_index')
    op.drop_column('users', 'current_topic')
    op.drop_table('useranswers')
    op.drop_table('skippedquestions')
    op.drop_table('questions')
    op.drop_table('topics')
    # ### end Alembic commands ###
